language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpcs --standard=PSR1 src/
  - vendor/bin/phpcs --standard=PSR2 src/
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls -v
